/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface ExchangeExtractorV4Interface extends ethers.utils.Interface {
  functions: {
    "getPairReserves(address,address[],address[])": FunctionFragment;
    "run(address[],bytes[])": FunctionFragment;
    "runSimple(address[],bytes[],address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getPairReserves",
    values: [string, string[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "run",
    values: [string[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "runSimple",
    values: [string[], BytesLike[], string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getPairReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "run", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "runSimple", data: BytesLike): Result;

  events: {};
}

export class ExchangeExtractorV4 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ExchangeExtractorV4Interface;

  functions: {
    getPairReserves(
      router: string,
      tokanAs: string[],
      tokenBs: string[],
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, string, BigNumber, BigNumber] & {
          token1: string;
          token2: string;
          reserve1: BigNumber;
          reserve2: BigNumber;
        })[],
        string
      ]
    >;

    run(
      addresses: string[],
      datas: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    runSimple(
      addresses: string[],
      datas: BytesLike[],
      token: string,
      amountIn: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getPairReserves(
    router: string,
    tokanAs: string[],
    tokenBs: string[],
    overrides?: CallOverrides
  ): Promise<
    [
      ([string, string, BigNumber, BigNumber] & {
        token1: string;
        token2: string;
        reserve1: BigNumber;
        reserve2: BigNumber;
      })[],
      string
    ]
  >;

  run(
    addresses: string[],
    datas: BytesLike[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  runSimple(
    addresses: string[],
    datas: BytesLike[],
    token: string,
    amountIn: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getPairReserves(
      router: string,
      tokanAs: string[],
      tokenBs: string[],
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, string, BigNumber, BigNumber] & {
          token1: string;
          token2: string;
          reserve1: BigNumber;
          reserve2: BigNumber;
        })[],
        string
      ]
    >;

    run(
      addresses: string[],
      datas: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    runSimple(
      addresses: string[],
      datas: BytesLike[],
      token: string,
      amountIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getPairReserves(
      router: string,
      tokanAs: string[],
      tokenBs: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    run(
      addresses: string[],
      datas: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    runSimple(
      addresses: string[],
      datas: BytesLike[],
      token: string,
      amountIn: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getPairReserves(
      router: string,
      tokanAs: string[],
      tokenBs: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    run(
      addresses: string[],
      datas: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    runSimple(
      addresses: string[],
      datas: BytesLike[],
      token: string,
      amountIn: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
